apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal-server
          image: 095132937849.dkr.ecr.us-east-1.amazonaws.com/temporal
          ports:
            - containerPort: 7233
          env:
            - name: TEMPORAL_NAMESPACE
              value: default
            - name: TEMPORAL_CLUSTER_NAME
              value: cluster
            - name: TEMPORAL_ADMIN_PASSWORD
              value: secret
            - name: TEMPORAL_SHARD_COUNT
              value: "1"